import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <h1>Sistema: Aprendendo Rotas</h1>
        <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/users">Users</Link></li>
            <li><Link href="/login">Logins</Link></li>
            <li><Link href="/getJson/eu">Sobre Mim</Link></li>
            <li><Link href="/useStateTeste">Usestat</Link></li>
            <li><Link href="/useEffectTeste">Use Effect</Link></li>
            <li><Link href="/useRefTeste">Use Ref</Link></li>
            <li><Link href="/useCallback">Use Callback</Link></li>
          </ul>
        </nav>
        <br />
        <hr />
        {children}
      </body>
    </html>
  );
}
